ALTER TABLE events ADD COLUMN IF NOT EXISTS cor TEXT NOT NULL DEFAULT '#2f4a3a';
ALTER TABLE events ADD COLUMN IF NOT EXISTS imagem TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS dresscode TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS presskit BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS endereco TEXT NOT NULL DEFAULT '';
